// THIS FILE WAS AUTOGENERATED BY:
// python3 scripts/res2header.py res/shaders/sprite_vert.glsl res/shaders/sprite_vert.h
#ifndef SHADERS_SPRITE_VERT_H_INCLUDED
#define SHADERS_SPRITE_VERT_H_INCLUDED

#include "shader.h"

static const char SHADER_SPRITE_VERT_PATH[] = "res/shaders/sprite_vert.glsl";
static const char SHADER_SPRITE_VERT_SOURCE[] = 
    "#version 330 core\n"
    "\n"
    "layout(location = 0) in vec3 a_position;\n"
    "layout(location = 1) in vec2 a_texcoord;\n"
    "\n"
    "out vec2 v_texcoord;\n"
    "\n"
    "uniform mat4 u_model;\n"
    "uniform mat4 u_projection;\n"
    "\n"
    "void main() {\n"
    "    v_texcoord = a_texcoord;\n"
    "    gl_Position = u_projection * u_model * vec4(a_position, 1.0f);\n"
    "}\n"
;

#endif
