// THIS FILE WAS AUTOGENERATED BY:
// python3 scripts/res2header.py res/shaders/font_frag.glsl res/shaders/font_frag.h
#ifndef SHADERS_FONT_FRAG_H_INCLUDED
#define SHADERS_FONT_FRAG_H_INCLUDED

#include "shader.h"

static const char SHADER_FONT_FRAG_PATH[] = "res/shaders/font_frag.glsl";
static const char SHADER_FONT_FRAG_SOURCE[] = 
    "#version 330 core\n"
    "\n"
    "out vec4 FragColor;\n"
    "\n"
    "void main() {\n"
    "    FragColor = vec4(1.0f, 1.0f, 1.0f, 1.0f);\n"
    "}\n"
;

#endif
