// THIS FILE WAS AUTOGENERATED BY:
// python3 scripts/res2header.py res/shaders/font_vert.glsl res/shaders/font_vert.h
#ifndef SHADERS_FONT_VERT_H_INCLUDED
#define SHADERS_FONT_VERT_H_INCLUDED

#include "shader.h"

static const char SHADER_FONT_VERT_PATH[] = "res/shaders/font_vert.glsl";
static const char SHADER_FONT_VERT_SOURCE[] = 
    "#version 330 core\n"
    "\n"
    "layout(location = 0) in vec2 a_position;\n"
    "\n"
    "uniform float u_layer;\n"
    "uniform mat4 u_model;\n"
    "uniform mat4 u_projection;\n"
    "\n"
    "void main() {\n"
    "    gl_Position = u_projection * u_model * vec4(a_position, u_layer, 1.0f);\n"
    "}\n"
;

#endif
