// THIS FILE WAS AUTOGENERATED BY:
// python3 scripts/res2header.py res/shaders/sprite_frag.glsl res/shaders/sprite_frag.h
#ifndef SHADERS_SPRITE_FRAG_H_INCLUDED
#define SHADERS_SPRITE_FRAG_H_INCLUDED

#include "shader.h"

static const char SHADER_SPRITE_FRAG_PATH[] = "res/shaders/sprite_frag.glsl";
static const char SHADER_SPRITE_FRAG_SOURCE[] = 
    "#version 330 core\n"
    "\n"
    "in vec2 v_texcoord;\n"
    "\n"
    "out vec4 FragColor;\n"
    "\n"
    "uniform sampler2D u_texture;\n"
    "\n"
    "void main() {\n"
    "    FragColor = texture(u_texture, v_texcoord);\n"
    "}\n"
;

#endif
