// THIS FILE WAS AUTOGENERATED BY:
// python3 scripts/res2header.py res/models/sprite.obj res/models/sprite.h
#ifndef MODELS_SPRITE_H_INCLUDED
#define MODELS_SPRITE_H_INCLUDED

#include "model.h"

static const char MODEL_SPRITE_PATH[] = "res/models/sprite.obj";
static const int MODEL_SPRITE_FORMAT = MODEL_FORMAT_T2F_V3F;
static const long MODEL_SPRITE_VERTEX_COUNT = 6;
static const float MODEL_SPRITE_VERTICES[] = {
     1.000000f,  1.000000f,  0.500000f,  0.500000f,  0.000000f,
     0.000000f,  1.000000f, -0.500000f,  0.500000f,  0.000000f,
     0.000000f,  0.000000f, -0.500000f, -0.500000f,  0.000000f,
     1.000000f,  1.000000f,  0.500000f,  0.500000f,  0.000000f,
     0.000000f,  0.000000f, -0.500000f, -0.500000f,  0.000000f,
     1.000000f,  0.000000f,  0.500000f, -0.500000f,  0.000000f,
};

#endif
