name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: make
        run: make -C 3_Implementation
      - name: install display
        run: sudo apt-get install xserver-xorg-video-dummy
      - name: setup display
        run: sudo echo -e "Section \"Device\"\n    Identifier  \"Configured Video Device\"\n    Driver      \"dummy\"\nEndSection\n\nSection \"Monitor\"\n    Identifier  \"Configured Monitor\"\n    HorizSync 31.5-48.5\n    VertRefresh 50-70\nEndSection\n\nSection \"Screen\"\n    Identifier  \"Default Screen\"\n    Monitor     \"Configured Monitor\"\n    Device      \"Configured Video Device\"\n    DefaultDepth 24\n    SubSection \"Display\"\n    Depth 24\n    Modes \"1024x800\"\n    EndSubSection\nEndSection" | sudo tee -a "/usr/share/X11/xorg.conf.d/xorg.conf"
      - name: setup display1
        run: sudo echo -e "Section \"Device\"\n    Identifier  \"Configured Video Device\"\n    Driver      \"dummy\"\nEndSection\n\nSection \"Monitor\"\n    Identifier  \"Configured Monitor\"\n    HorizSync 31.5-48.5\n    VertRefresh 50-70\nEndSection\n\nSection \"Screen\"\n    Identifier  \"Default Screen\"\n    Monitor     \"Configured Monitor\"\n    Device      \"Configured Video Device\"\n    DefaultDepth 24\n    SubSection \"Display\"\n    Depth 24\n    Modes \"1024x800\"\n    EndSubSection\nEndSection" | sudo tee -a "/etc/X11/xorg.conf"

      - name: test
        run: 3_Implementation/test

