name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install
        run: sudo apt-get install libglfw3-dev&&pip3 install wheel pillow pywavefront
      - name: make
        run: make -C 3_Implementation
      - name: test
        run: ls 3_Implementation| grep test

