name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: make
        run: make -C 3_Implementation
      - name: envvar
        run: echo "DISPLAY=0">> $GITHUB_ENV;
      - name: test
        run: 3_Implementation/test

